"""prompt cache token accounting

Revision ID: 06c34da52ce8
Revises: b49835e1be30
Create Date: 2026-09-10 23:23:59.995728
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "06c34da52ce8"
down_revision: str | None = "b49835e1be30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("extractions", sa.Column("cache_write_tokens", sa.Integer(), nullable=True))
    op.add_column("extractions", sa.Column("cache_read_tokens", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("extractions", "cache_read_tokens")
    op.drop_column("extractions", "cache_write_tokens")
    # ### end Alembic commands ###
