"""initial schema

Revision ID: 9e72c3a5a82f
Revises:
Create Date: 2026-09-10 19:48:50.884714
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9e72c3a5a82f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any vector column is created. The Compose init
    # script also does this, but a CI service container or a fresh database does
    # not run it, so the migration has to be self-sufficient.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("external_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_type IS NULL OR entity_type IN ('armed_group', 'company', 'government_body', 'industry_group', 'infrastructure', 'other_organisation', 'port_authority', 'regulatory_authority', 'state', 'vessel', 'vessel_class')",
            name=op.f("ck_entities_entity_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
        sa.UniqueConstraint(
            "canonical_name", "entity_type", name="uq_entities_canonical_name_entity_type"
        ),
    )
    op.create_table(
        "evaluation_datasets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_datasets")),
        sa.UniqueConstraint("name", "version", name="uq_evaluation_datasets_name_version"),
    )
    op.create_table(
        "event_clusters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("centroid", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("similarity_threshold", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_clusters")),
    )
    op.create_table(
        "prompts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("template_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "template_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_prompts_template_hash_is_sha256")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompts")),
        sa.UniqueConstraint("name", "version", name="uq_prompts_name_version"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("publisher", sa.String(length=200), nullable=False),
        sa.Column("homepage_url", sa.Text(), nullable=True),
        sa.Column("feed_url", sa.Text(), nullable=False),
        sa.Column("retrieval_method", sa.String(length=32), nullable=False),
        sa.Column("poll_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("terms_url", sa.Text(), nullable=True),
        sa.Column("terms_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("terms_reviewed_by", sa.String(length=200), nullable=True),
        sa.Column("terms_note", sa.Text(), nullable=True),
        sa.Column("licence", sa.String(length=200), nullable=True),
        sa.Column("robots_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("store_full_text", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "retrieval_method IS NULL OR retrieval_method IN ('api', 'bulk_file', 'notice_html', 'rss')",
            name=op.f("ck_sources_retrieval_method"),
        ),
        sa.CheckConstraint(
            "NOT enabled OR terms_reviewed_at IS NOT NULL",
            name=op.f("ck_sources_ck_sources_enabled_requires_terms_review"),
        ),
        sa.CheckConstraint(
            "NOT store_full_text OR terms_reviewed_at IS NOT NULL",
            name=op.f("ck_sources_ck_sources_full_text_requires_terms_review"),
        ),
        sa.CheckConstraint(
            "poll_interval_seconds BETWEEN 1800 AND 3600",
            name=op.f("ck_sources_ck_sources_poll_interval_30_to_60_min"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("slug", name=op.f("uq_sources_slug")),
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("run_label", sa.String(length=200), nullable=True),
        sa.Column("git_sha", sa.String(length=40), nullable=True),
        sa.Column("prompt_name", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("model_name", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["evaluation_datasets.id"],
            name=op.f("fk_evaluation_runs_dataset_id_evaluation_datasets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_table(
        "events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_time_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("severity_rationale", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("change_note", sa.Text(), nullable=True),
        sa.Column("superseded_by", sa.UUID(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IS NULL OR event_type IN ('canal_transit_restriction', 'customs_or_border_delay', 'energy_export_restriction', 'labor_action_transport', 'lng_terminal_disruption', 'maritime_security_advisory', 'other_in_scope', 'pipeline_disruption', 'piracy_or_armed_robbery_report', 'port_disruption', 'power_grid_disruption', 'refinery_outage', 'sanctions_or_regulatory_notice', 'strait_transit_restriction', 'subsea_cable_damage', 'supply_chain_shortage_notice', 'vessel_incident')",
            name=op.f("ck_events_event_type"),
        ),
        sa.CheckConstraint(
            "review_status IS NULL OR review_status IN ('approved', 'edited', 'not_required', 'pending', 'rejected')",
            name=op.f("ck_events_review_status"),
        ),
        sa.CheckConstraint(
            "severity IS NULL OR severity IN ('high', 'informational', 'low', 'moderate', 'severe')",
            name=op.f("ck_events_severity"),
        ),
        sa.CheckConstraint(
            "severity NOT IN ('high', 'severe') OR requires_human_review",
            name=op.f("ck_events_ck_events_high_severity_requires_review"),
        ),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('active', 'merged', 'resolved', 'superseded')",
            name=op.f("ck_events_status"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_events_ck_events_confidence_in_unit_interval"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence >= 0.60 OR requires_human_review",
            name=op.f("ck_events_ck_events_low_confidence_requires_review"),
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["event_clusters.id"],
            name=op.f("fk_events_cluster_id_event_clusters"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by"],
            ["events.event_id"],
            name=op.f("fk_events_superseded_by_events"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_events")),
    )
    op.create_index("ix_events_event_date", "events", ["event_date"], unique=False)
    op.create_index("ix_events_event_type", "events", ["event_type"], unique=False)
    op.create_index(
        "ix_events_requires_human_review", "events", ["requires_human_review"], unique=False
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("items_seen", sa.Integer(), nullable=False),
        sa.Column("items_new", sa.Integer(), nullable=False),
        sa.Column("items_duplicate", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("http_requests", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IS NULL OR status IN ('failed', 'running', 'skipped', 'succeeded')",
            name=op.f("ck_ingestion_runs_status"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_ingestion_runs_source_id_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        op.f("ix_ingestion_runs_source_id"), "ingestion_runs", ["source_id"], unique=False
    )
    op.create_table(
        "event_actors",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "role IS NULL OR role IN ('affected_party', 'authority_issuing_notice', 'claimed_responsible', 'mentioned', 'operator', 'owner')",
            name=op.f("ck_event_actors_role"),
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
            name=op.f("fk_event_actors_entity_id_entities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_actors_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "entity_id", "role", name=op.f("pk_event_actors")),
    )
    op.create_table(
        "event_locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("location_type", sa.String(length=32), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("admin_area", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=8, scale=5), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=8, scale=5), nullable=True),
        sa.Column("location_precision", sa.String(length=32), nullable=True),
        sa.Column("geo_source", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "country_code IS NULL OR country_code ~ '^[A-Z]{2}$'",
            name=op.f("ck_event_locations_ck_event_locations_country_code_is_iso_alpha2"),
        ),
        sa.CheckConstraint(
            "location_precision IS NULL OR location_precision IN ('admin_area', 'approximate', 'country', 'facility', 'sea_area')",
            name=op.f("ck_event_locations_location_precision"),
        ),
        sa.CheckConstraint(
            "location_type IS NULL OR location_type IN ('admin_area', 'canal', 'country', 'eez', 'grid_region', 'pipeline', 'port', 'refinery', 'sea_area', 'shipping_lane', 'strait', 'subsea_cable_segment', 'terminal')",
            name=op.f("ck_event_locations_location_type"),
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)",
            name=op.f("ck_event_locations_ck_event_locations_latitude_range"),
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)",
            name=op.f("ck_event_locations_ck_event_locations_longitude_range"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_locations_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_locations")),
    )
    op.create_index(
        op.f("ix_event_locations_event_id"), "event_locations", ["event_id"], unique=False
    )
    op.create_table(
        "event_sectors",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("sector", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "sector IS NULL OR sector IN ('air_cargo', 'electricity', 'lng', 'maritime_shipping', 'natural_gas', 'oil', 'ports_terminals', 'rail_freight', 'refined_products', 'road_freight', 'telecoms_subsea')",
            name=op.f("ck_event_sectors_sector"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_sectors_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "sector", name=op.f("pk_event_sectors")),
    )
    op.create_table(
        "raw_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("fetch_run_id", sa.UUID(), nullable=True),
        sa.Column("source_uid", sa.String(length=512), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieval_method", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("etag", sa.String(length=256), nullable=True),
        sa.Column("last_modified", sa.String(length=128), nullable=True),
        sa.Column("raw_body", sa.Text(), nullable=True),
        sa.Column("clean_text", sa.Text(), nullable=True),
        sa.Column("raw_hash", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("is_tombstoned", sa.Boolean(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_raw_documents_content_hash_is_sha256")
        ),
        sa.CheckConstraint(
            "raw_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_raw_documents_raw_hash_is_sha256")
        ),
        sa.CheckConstraint(
            "retrieval_method IS NULL OR retrieval_method IN ('api', 'bulk_file', 'notice_html', 'rss')",
            name=op.f("ck_raw_documents_retrieval_method"),
        ),
        sa.CheckConstraint(
            "NOT is_tombstoned OR (raw_body IS NULL AND clean_text IS NULL)",
            name=op.f("ck_raw_documents_ck_raw_documents_tombstoned_has_no_content"),
        ),
        sa.ForeignKeyConstraint(
            ["fetch_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_raw_documents_fetch_run_id_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_raw_documents_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_documents")),
        sa.UniqueConstraint(
            "source_id", "content_hash", name="uq_raw_documents_source_content_hash"
        ),
    )
    op.create_index(
        "ix_raw_documents_published_at", "raw_documents", ["published_at"], unique=False
    )
    op.create_index(
        "ix_raw_documents_retrieved_at", "raw_documents", ["retrieved_at"], unique=False
    )
    op.create_index(
        "ix_raw_documents_source_id_source_uid",
        "raw_documents",
        ["source_id", "source_uid"],
        unique=False,
    )
    op.create_table(
        "review_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("reviewer", sa.String(length=200), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IS NULL OR decision IN ('approve', 'edit', 'reject')",
            name=op.f("ck_review_decisions_decision"),
        ),
        sa.CheckConstraint(
            "length(btrim(reason)) > 0",
            name=op.f("ck_review_decisions_ck_review_decisions_reason_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_review_decisions_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_decisions")),
    )
    op.create_index(
        op.f("ix_review_decisions_event_id"), "review_decisions", ["event_id"], unique=False
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding_dim", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_end > char_start",
            name=op.f("ck_document_chunks_ck_document_chunks_offsets_ordered"),
        ),
        sa.CheckConstraint(
            "char_start >= 0",
            name=op.f("ck_document_chunks_ck_document_chunks_offsets_non_negative"),
        ),
        sa.CheckConstraint(
            "embedding IS NULL OR embedding_model IS NOT NULL",
            name=op.f("ck_document_chunks_ck_document_chunks_embedding_records_model"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["raw_documents.id"],
            name=op.f("fk_document_chunks_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name="uq_document_chunks_document_id_chunk_index"
        ),
    )
    op.create_table(
        "evaluation_examples",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("external_ref", sa.String(length=512), nullable=True),
        sa.Column("label_type", sa.String(length=32), nullable=False),
        sa.Column("expected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "label_type IS NULL OR label_type IN ('background', 'duplicate', 'insufficient_evidence', 'new_event', 'update')",
            name=op.f("ck_evaluation_examples_label_type"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["evaluation_datasets.id"],
            name=op.f("fk_evaluation_examples_dataset_id_evaluation_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["raw_documents.id"],
            name=op.f("fk_evaluation_examples_document_id_raw_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_examples")),
    )
    op.create_index(
        op.f("ix_evaluation_examples_dataset_id"),
        "evaluation_examples",
        ["dataset_id"],
        unique=False,
    )
    op.create_table(
        "event_documents",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column(
            "first_linked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation IS NULL OR relation IN ('background', 'duplicate', 'new_event', 'update')",
            name=op.f("ck_event_documents_relation"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["raw_documents.id"],
            name=op.f("fk_event_documents_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_documents_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", "document_id", name=op.f("pk_event_documents")),
    )
    op.create_table(
        "event_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("field_supported", sa.String(length=64), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("quote_char_start", sa.Integer(), nullable=True),
        sa.Column("quote_char_end", sa.Integer(), nullable=True),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verification_method", sa.String(length=64), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT verified OR (verification_method IS NOT NULL AND verified_at IS NOT NULL)",
            name=op.f("ck_event_evidence_ck_event_evidence_verified_records_method"),
        ),
        sa.CheckConstraint(
            "length(btrim(quote)) > 0",
            name=op.f("ck_event_evidence_ck_event_evidence_quote_not_blank"),
        ),
        sa.CheckConstraint(
            "quote_char_start IS NULL OR quote_char_end IS NULL OR quote_char_end > quote_char_start",
            name=op.f("ck_event_evidence_ck_event_evidence_offsets_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["raw_documents.id"],
            name=op.f("fk_event_evidence_document_id_raw_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_event_evidence_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_evidence")),
    )
    op.create_index(
        op.f("ix_event_evidence_event_id"), "event_evidence", ["event_id"], unique=False
    )
    op.create_table(
        "extractions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=True),
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=True),
        sa.Column("temperature", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("schema_valid", sa.Boolean(), nullable=True),
        sa.Column("citation_valid", sa.Boolean(), nullable=True),
        sa.Column("citations_checked", sa.Integer(), nullable=False),
        sa.Column("citations_failed", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IS NULL OR outcome IN ('abstained', 'citation_invalid', 'error', 'extracted', 'schema_invalid')",
            name=op.f("ck_extractions_outcome"),
        ),
        sa.CheckConstraint(
            "citations_checked >= 0",
            name=op.f("ck_extractions_ck_extractions_citations_non_negative"),
        ),
        sa.CheckConstraint(
            "citations_failed <= citations_checked",
            name=op.f("ck_extractions_ck_extractions_failed_le_checked"),
        ),
        sa.CheckConstraint(
            "event_id IS NULL OR (schema_valid AND citation_valid)",
            name=op.f(
                "ck_extractions_ck_extractions_published_requires_valid_schema_and_citations"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["raw_documents.id"],
            name=op.f("fk_extractions_document_id_raw_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.event_id"],
            name=op.f("fk_extractions_event_id_events"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
            name=op.f("fk_extractions_prompt_id_prompts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extractions")),
    )
    op.create_index(
        op.f("ix_extractions_document_id"), "extractions", ["document_id"], unique=False
    )
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("example_id", sa.UUID(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("actual", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["example_id"],
            ["evaluation_examples.id"],
            name=op.f("fk_evaluation_results_example_id_evaluation_examples"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["evaluation_runs.id"],
            name=op.f("fk_evaluation_results_run_id_evaluation_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_results")),
        sa.UniqueConstraint("run_id", "example_id", name="uq_evaluation_results_run_id_example_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # The 'vector' extension is intentionally left in place: dropping it would
    # affect any other schema in this database that uses it.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evaluation_results")
    op.drop_index(op.f("ix_extractions_document_id"), table_name="extractions")
    op.drop_table("extractions")
    op.drop_index(op.f("ix_event_evidence_event_id"), table_name="event_evidence")
    op.drop_table("event_evidence")
    op.drop_table("event_documents")
    op.drop_index(op.f("ix_evaluation_examples_dataset_id"), table_name="evaluation_examples")
    op.drop_table("evaluation_examples")
    op.drop_table("document_chunks")
    op.drop_index(op.f("ix_review_decisions_event_id"), table_name="review_decisions")
    op.drop_table("review_decisions")
    op.drop_index("ix_raw_documents_source_id_source_uid", table_name="raw_documents")
    op.drop_index("ix_raw_documents_retrieved_at", table_name="raw_documents")
    op.drop_index("ix_raw_documents_published_at", table_name="raw_documents")
    op.drop_table("raw_documents")
    op.drop_table("event_sectors")
    op.drop_index(op.f("ix_event_locations_event_id"), table_name="event_locations")
    op.drop_table("event_locations")
    op.drop_table("event_actors")
    op.drop_index(op.f("ix_ingestion_runs_source_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_index("ix_events_requires_human_review", table_name="events")
    op.drop_index("ix_events_event_type", table_name="events")
    op.drop_index("ix_events_event_date", table_name="events")
    op.drop_table("events")
    op.drop_table("evaluation_runs")
    op.drop_table("sources")
    op.drop_table("prompts")
    op.drop_table("event_clusters")
    op.drop_table("evaluation_datasets")
    op.drop_table("entities")
    # ### end Alembic commands ###
