"""embedding dimension 384

Revision ID: b49835e1be30
Revises: d31f7a4b90c2
Create Date: 2026-09-10 21:37:10.105634
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "b49835e1be30"
down_revision: str | None = "d31f7a4b90c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _refuse_if_embeddings_exist() -> None:
    """Narrowing a vector column silently discards nothing only while it is empty.

    ADR-0002 D1 is explicit that changing the dimension is cheap *now* because no source
    has ever been enabled and there is nothing to re-embed. Once real vectors exist, this
    is no longer a schema change -- it is a re-embed of the whole corpus, and it must be
    written as one. Failing here is much better than a migration that appears to succeed
    and leaves the corpus unsearchable.
    """
    connection = op.get_bind()
    for table, column in (("document_chunks", "embedding"), ("event_clusters", "centroid")):
        count = connection.execute(
            sa.text(f"SELECT count(*) FROM {table} WHERE {column} IS NOT NULL")  # noqa: S608
        ).scalar_one()
        if count:
            raise RuntimeError(
                f"{table}.{column} holds {count} vector(s) at the old dimension. "
                "Changing the embedding dimension requires re-embedding the corpus; "
                "write that migration explicitly rather than running this one."
            )


def upgrade() -> None:
    _refuse_if_embeddings_exist()

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=True,
    )
    op.alter_column(
        "event_clusters",
        "centroid",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    _refuse_if_embeddings_exist()

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "event_clusters",
        "centroid",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        existing_nullable=True,
    )
    op.alter_column(
        "document_chunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
