"""source fetch state and adapter verification flags

Revision ID: ce4c9dc8c0e8
Revises: 9e72c3a5a82f
Create Date: 2026-09-10 20:05:47.904133
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ce4c9dc8c0e8"
down_revision: str | None = "9e72c3a5a82f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources",
        sa.Column(
            "endpoint_verified", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "sources",
        sa.Column(
            "format_confirmed", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column("sources", sa.Column("last_etag", sa.String(length=256), nullable=True))
    op.add_column(
        "sources", sa.Column("last_modified_header", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "sources", sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "sources", sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "sources",
        sa.Column(
            "consecutive_failures", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column("sources", sa.Column("disabled_reason", sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate does not detect CHECK constraints; these are written by hand.
    # An enabled source must run on a confirmed endpoint and a confirmed parse, not
    # on the registry's starting hypothesis.
    op.create_check_constraint(
        "enabled_requires_verified_adapter",
        "sources",
        "NOT enabled OR (endpoint_verified AND format_confirmed)",
    )
    op.create_check_constraint(
        "consecutive_failures_non_negative",
        "sources",
        "consecutive_failures >= 0",
    )


def downgrade() -> None:
    op.drop_constraint("ck_sources_consecutive_failures_non_negative", "sources", type_="check")
    op.drop_constraint("ck_sources_enabled_requires_verified_adapter", "sources", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sources", "disabled_reason")
    op.drop_column("sources", "consecutive_failures")
    op.drop_column("sources", "last_success_at")
    op.drop_column("sources", "last_fetched_at")
    op.drop_column("sources", "last_modified_header")
    op.drop_column("sources", "last_etag")
    op.drop_column("sources", "format_confirmed")
    op.drop_column("sources", "endpoint_verified")
    # ### end Alembic commands ###
